### PR TITLE
fixed playersinfo & minor optimizations

### PR DESCRIPTION
**Pull request by ado1928**
-fixed playersinfo
-dont run verification if player is banned
-the verification is under a try block

I haven't actually tested any of these, as im too lazy to set it all up.
Test it before actually adding the plugin

### CODE REVIEW

**Comment by fuzzbuck** [comment]
remove the verification edit & resolve conflics and i will merge

**Comment by ado1928** [comment]
you can do that too, you know

**Comment by fuzzbuck** [comment]
verification was changed & the way you do playersinfo is you split the message x times, but dont actually put the corresponding tags (```) so it doens't correctly wrap.

im planning on getting rid of playerinfo and adding a sophisticated lookup command

**Comment by ado1928** [comment]
wait a sec, did that delete the file, or the changes?

**Comment by ado1928** [comment]
anyways, im gonna close this pr, because you have different plans

**Pull request closed without merging**
